id: P1A143048
initial_creation_type: input
source_metadata:
  title: Nyāyapariśuddhi, Bhūmikā, 1, 3-5
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Nyāya
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:03:51.054237'
last_modified_at: '2022-03-09T15:03:51.054250'
